name: CI

on: 
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering

jobs:
  echo-job:
    runs-on: ubuntu-latest

    steps:
    - name: Step 1
      run: echo "Step 1 complete!"

    - name: Step 2
      run: echo "Step 2 complete!"